services:
  kinetic:
    build: .
    container_name: kinetic-typography
    env_file: .env
    environment:
      - WEBHOOK_PORT=4000
    volumes:
      - ./output:/app/output
      - ./.cache:/app/.cache
      - ./config:/app/config
      - ./data:/app/data
      - ./public:/app/public
    ports:
      - "4000:4000"
    restart: unless-stopped
